// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package persistence

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	Guid      pgtype.UUID
	Createdat pgtype.Timestamp
	Name      string
	Login     string
	Password  string
}

type Generalexercise struct {
	Guid        pgtype.UUID
	Adminguid   pgtype.UUID
	Name        string
	Description string
}

type User struct {
	Guid      pgtype.UUID
	Createdat pgtype.Timestamp
	Name      string
	Login     string
	Password  string
}

type Userexercise struct {
	Guid        pgtype.UUID
	Userguid    pgtype.UUID
	Name        string
	Description string
}

type Workout struct {
	Guid              pgtype.UUID
	Userguid          pgtype.UUID
	Scheduledfor      pgtype.Timestamp
	Durationinminutes float64
	Setsandbreaks     []byte
}
